name: flulator
description: Open Source Flutter calculator.

publish_to: 'none'

version: 2.4.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  math_expressions: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "asset/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - asset/logo.jpg
    - asset/header.jpg